# This file defines the standard configuration for the FLArE only option
# The geometry contains only FLArE (TPC + HadCather + MuonFinder)

/det/fileGdml FLArE_only.gdml

# Configuring FLArE
/det/addFLArE true
/det/flare/addFLArEPos 0 0 4300 mm
/det/flare/material LAr
/det/flare/module 3x7
/det/flare/field 1. tesla
/det/flare/useBabyMIND false

# Turn off everything else
/det/addFORMOSA false
/det/addFASERnu2 false
/det/addFASER2 false
