# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.20

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /cvmfs/larsoft.opensciencegrid.org/products/cmake/v3_20_0/Linux64bit+3.10-2.17/bin/cmake

# The command to remove a file.
RM = /cvmfs/larsoft.opensciencegrid.org/products/cmake/v3_20_0/Linux64bit+3.10-2.17/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /dune/app/users/wenjiewu/FLArE_Dev/FLArE

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /dune/app/users/wenjiewu/FLArE_Dev/FLArE

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/cvmfs/larsoft.opensciencegrid.org/products/cmake/v3_20_0/Linux64bit+3.10-2.17/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/cvmfs/larsoft.opensciencegrid.org/products/cmake/v3_20_0/Linux64bit+3.10-2.17/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/cvmfs/larsoft.opensciencegrid.org/products/cmake/v3_20_0/Linux64bit+3.10-2.17/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/cvmfs/larsoft.opensciencegrid.org/products/cmake/v3_20_0/Linux64bit+3.10-2.17/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/cvmfs/larsoft.opensciencegrid.org/products/cmake/v3_20_0/Linux64bit+3.10-2.17/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/cvmfs/larsoft.opensciencegrid.org/products/cmake/v3_20_0/Linux64bit+3.10-2.17/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/cvmfs/larsoft.opensciencegrid.org/products/cmake/v3_20_0/Linux64bit+3.10-2.17/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/cvmfs/larsoft.opensciencegrid.org/products/cmake/v3_20_0/Linux64bit+3.10-2.17/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /dune/app/users/wenjiewu/FLArE_Dev/FLArE/CMakeFiles /dune/app/users/wenjiewu/FLArE_Dev/FLArE//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /dune/app/users/wenjiewu/FLArE_Dev/FLArE/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named FLArE

# Build rule for target.
FLArE: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 FLArE
.PHONY : FLArE

# fast build rule for target.
FLArE/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/FLArE.dir/build.make CMakeFiles/FLArE.dir/build
.PHONY : FLArE/fast

FLArE.o: FLArE.cc.o
.PHONY : FLArE.o

# target to build an object file
FLArE.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/FLArE.dir/build.make CMakeFiles/FLArE.dir/FLArE.cc.o
.PHONY : FLArE.cc.o

FLArE.i: FLArE.cc.i
.PHONY : FLArE.i

# target to preprocess a source file
FLArE.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/FLArE.dir/build.make CMakeFiles/FLArE.dir/FLArE.cc.i
.PHONY : FLArE.cc.i

FLArE.s: FLArE.cc.s
.PHONY : FLArE.s

# target to generate assembly for a file
FLArE.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/FLArE.dir/build.make CMakeFiles/FLArE.dir/FLArE.cc.s
.PHONY : FLArE.cc.s

src/ActionInitialization.o: src/ActionInitialization.cc.o
.PHONY : src/ActionInitialization.o

# target to build an object file
src/ActionInitialization.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/FLArE.dir/build.make CMakeFiles/FLArE.dir/src/ActionInitialization.cc.o
.PHONY : src/ActionInitialization.cc.o

src/ActionInitialization.i: src/ActionInitialization.cc.i
.PHONY : src/ActionInitialization.i

# target to preprocess a source file
src/ActionInitialization.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/FLArE.dir/build.make CMakeFiles/FLArE.dir/src/ActionInitialization.cc.i
.PHONY : src/ActionInitialization.cc.i

src/ActionInitialization.s: src/ActionInitialization.cc.s
.PHONY : src/ActionInitialization.s

# target to generate assembly for a file
src/ActionInitialization.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/FLArE.dir/build.make CMakeFiles/FLArE.dir/src/ActionInitialization.cc.s
.PHONY : src/ActionInitialization.cc.s

src/AnalysisManager.o: src/AnalysisManager.cc.o
.PHONY : src/AnalysisManager.o

# target to build an object file
src/AnalysisManager.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/FLArE.dir/build.make CMakeFiles/FLArE.dir/src/AnalysisManager.cc.o
.PHONY : src/AnalysisManager.cc.o

src/AnalysisManager.i: src/AnalysisManager.cc.i
.PHONY : src/AnalysisManager.i

# target to preprocess a source file
src/AnalysisManager.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/FLArE.dir/build.make CMakeFiles/FLArE.dir/src/AnalysisManager.cc.i
.PHONY : src/AnalysisManager.cc.i

src/AnalysisManager.s: src/AnalysisManager.cc.s
.PHONY : src/AnalysisManager.s

# target to generate assembly for a file
src/AnalysisManager.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/FLArE.dir/build.make CMakeFiles/FLArE.dir/src/AnalysisManager.cc.s
.PHONY : src/AnalysisManager.cc.s

src/AnalysisManagerMessenger.o: src/AnalysisManagerMessenger.cc.o
.PHONY : src/AnalysisManagerMessenger.o

# target to build an object file
src/AnalysisManagerMessenger.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/FLArE.dir/build.make CMakeFiles/FLArE.dir/src/AnalysisManagerMessenger.cc.o
.PHONY : src/AnalysisManagerMessenger.cc.o

src/AnalysisManagerMessenger.i: src/AnalysisManagerMessenger.cc.i
.PHONY : src/AnalysisManagerMessenger.i

# target to preprocess a source file
src/AnalysisManagerMessenger.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/FLArE.dir/build.make CMakeFiles/FLArE.dir/src/AnalysisManagerMessenger.cc.i
.PHONY : src/AnalysisManagerMessenger.cc.i

src/AnalysisManagerMessenger.s: src/AnalysisManagerMessenger.cc.s
.PHONY : src/AnalysisManagerMessenger.s

# target to generate assembly for a file
src/AnalysisManagerMessenger.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/FLArE.dir/build.make CMakeFiles/FLArE.dir/src/AnalysisManagerMessenger.cc.s
.PHONY : src/AnalysisManagerMessenger.cc.s

src/DetectorConstruction.o: src/DetectorConstruction.cc.o
.PHONY : src/DetectorConstruction.o

# target to build an object file
src/DetectorConstruction.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/FLArE.dir/build.make CMakeFiles/FLArE.dir/src/DetectorConstruction.cc.o
.PHONY : src/DetectorConstruction.cc.o

src/DetectorConstruction.i: src/DetectorConstruction.cc.i
.PHONY : src/DetectorConstruction.i

# target to preprocess a source file
src/DetectorConstruction.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/FLArE.dir/build.make CMakeFiles/FLArE.dir/src/DetectorConstruction.cc.i
.PHONY : src/DetectorConstruction.cc.i

src/DetectorConstruction.s: src/DetectorConstruction.cc.s
.PHONY : src/DetectorConstruction.s

# target to generate assembly for a file
src/DetectorConstruction.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/FLArE.dir/build.make CMakeFiles/FLArE.dir/src/DetectorConstruction.cc.s
.PHONY : src/DetectorConstruction.cc.s

src/DetectorConstructionMaterial.o: src/DetectorConstructionMaterial.cc.o
.PHONY : src/DetectorConstructionMaterial.o

# target to build an object file
src/DetectorConstructionMaterial.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/FLArE.dir/build.make CMakeFiles/FLArE.dir/src/DetectorConstructionMaterial.cc.o
.PHONY : src/DetectorConstructionMaterial.cc.o

src/DetectorConstructionMaterial.i: src/DetectorConstructionMaterial.cc.i
.PHONY : src/DetectorConstructionMaterial.i

# target to preprocess a source file
src/DetectorConstructionMaterial.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/FLArE.dir/build.make CMakeFiles/FLArE.dir/src/DetectorConstructionMaterial.cc.i
.PHONY : src/DetectorConstructionMaterial.cc.i

src/DetectorConstructionMaterial.s: src/DetectorConstructionMaterial.cc.s
.PHONY : src/DetectorConstructionMaterial.s

# target to generate assembly for a file
src/DetectorConstructionMaterial.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/FLArE.dir/build.make CMakeFiles/FLArE.dir/src/DetectorConstructionMaterial.cc.s
.PHONY : src/DetectorConstructionMaterial.cc.s

src/DetectorConstructionMessenger.o: src/DetectorConstructionMessenger.cc.o
.PHONY : src/DetectorConstructionMessenger.o

# target to build an object file
src/DetectorConstructionMessenger.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/FLArE.dir/build.make CMakeFiles/FLArE.dir/src/DetectorConstructionMessenger.cc.o
.PHONY : src/DetectorConstructionMessenger.cc.o

src/DetectorConstructionMessenger.i: src/DetectorConstructionMessenger.cc.i
.PHONY : src/DetectorConstructionMessenger.i

# target to preprocess a source file
src/DetectorConstructionMessenger.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/FLArE.dir/build.make CMakeFiles/FLArE.dir/src/DetectorConstructionMessenger.cc.i
.PHONY : src/DetectorConstructionMessenger.cc.i

src/DetectorConstructionMessenger.s: src/DetectorConstructionMessenger.cc.s
.PHONY : src/DetectorConstructionMessenger.s

# target to generate assembly for a file
src/DetectorConstructionMessenger.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/FLArE.dir/build.make CMakeFiles/FLArE.dir/src/DetectorConstructionMessenger.cc.s
.PHONY : src/DetectorConstructionMessenger.cc.s

src/EventAction.o: src/EventAction.cc.o
.PHONY : src/EventAction.o

# target to build an object file
src/EventAction.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/FLArE.dir/build.make CMakeFiles/FLArE.dir/src/EventAction.cc.o
.PHONY : src/EventAction.cc.o

src/EventAction.i: src/EventAction.cc.i
.PHONY : src/EventAction.i

# target to preprocess a source file
src/EventAction.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/FLArE.dir/build.make CMakeFiles/FLArE.dir/src/EventAction.cc.i
.PHONY : src/EventAction.cc.i

src/EventAction.s: src/EventAction.cc.s
.PHONY : src/EventAction.s

# target to generate assembly for a file
src/EventAction.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/FLArE.dir/build.make CMakeFiles/FLArE.dir/src/EventAction.cc.s
.PHONY : src/EventAction.cc.s

src/FLArEPhysicsList.o: src/FLArEPhysicsList.cc.o
.PHONY : src/FLArEPhysicsList.o

# target to build an object file
src/FLArEPhysicsList.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/FLArE.dir/build.make CMakeFiles/FLArE.dir/src/FLArEPhysicsList.cc.o
.PHONY : src/FLArEPhysicsList.cc.o

src/FLArEPhysicsList.i: src/FLArEPhysicsList.cc.i
.PHONY : src/FLArEPhysicsList.i

# target to preprocess a source file
src/FLArEPhysicsList.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/FLArE.dir/build.make CMakeFiles/FLArE.dir/src/FLArEPhysicsList.cc.i
.PHONY : src/FLArEPhysicsList.cc.i

src/FLArEPhysicsList.s: src/FLArEPhysicsList.cc.s
.PHONY : src/FLArEPhysicsList.s

# target to generate assembly for a file
src/FLArEPhysicsList.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/FLArE.dir/build.make CMakeFiles/FLArE.dir/src/FLArEPhysicsList.cc.s
.PHONY : src/FLArEPhysicsList.cc.s

src/FLArETrackInformation.o: src/FLArETrackInformation.cc.o
.PHONY : src/FLArETrackInformation.o

# target to build an object file
src/FLArETrackInformation.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/FLArE.dir/build.make CMakeFiles/FLArE.dir/src/FLArETrackInformation.cc.o
.PHONY : src/FLArETrackInformation.cc.o

src/FLArETrackInformation.i: src/FLArETrackInformation.cc.i
.PHONY : src/FLArETrackInformation.i

# target to preprocess a source file
src/FLArETrackInformation.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/FLArE.dir/build.make CMakeFiles/FLArE.dir/src/FLArETrackInformation.cc.i
.PHONY : src/FLArETrackInformation.cc.i

src/FLArETrackInformation.s: src/FLArETrackInformation.cc.s
.PHONY : src/FLArETrackInformation.s

# target to generate assembly for a file
src/FLArETrackInformation.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/FLArE.dir/build.make CMakeFiles/FLArE.dir/src/FLArETrackInformation.cc.s
.PHONY : src/FLArETrackInformation.cc.s

src/FLArETrackingAction.o: src/FLArETrackingAction.cc.o
.PHONY : src/FLArETrackingAction.o

# target to build an object file
src/FLArETrackingAction.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/FLArE.dir/build.make CMakeFiles/FLArE.dir/src/FLArETrackingAction.cc.o
.PHONY : src/FLArETrackingAction.cc.o

src/FLArETrackingAction.i: src/FLArETrackingAction.cc.i
.PHONY : src/FLArETrackingAction.i

# target to preprocess a source file
src/FLArETrackingAction.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/FLArE.dir/build.make CMakeFiles/FLArE.dir/src/FLArETrackingAction.cc.i
.PHONY : src/FLArETrackingAction.cc.i

src/FLArETrackingAction.s: src/FLArETrackingAction.cc.s
.PHONY : src/FLArETrackingAction.s

# target to generate assembly for a file
src/FLArETrackingAction.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/FLArE.dir/build.make CMakeFiles/FLArE.dir/src/FLArETrackingAction.cc.s
.PHONY : src/FLArETrackingAction.cc.s

src/GENIEPrimaryGeneratorAction.o: src/GENIEPrimaryGeneratorAction.cc.o
.PHONY : src/GENIEPrimaryGeneratorAction.o

# target to build an object file
src/GENIEPrimaryGeneratorAction.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/FLArE.dir/build.make CMakeFiles/FLArE.dir/src/GENIEPrimaryGeneratorAction.cc.o
.PHONY : src/GENIEPrimaryGeneratorAction.cc.o

src/GENIEPrimaryGeneratorAction.i: src/GENIEPrimaryGeneratorAction.cc.i
.PHONY : src/GENIEPrimaryGeneratorAction.i

# target to preprocess a source file
src/GENIEPrimaryGeneratorAction.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/FLArE.dir/build.make CMakeFiles/FLArE.dir/src/GENIEPrimaryGeneratorAction.cc.i
.PHONY : src/GENIEPrimaryGeneratorAction.cc.i

src/GENIEPrimaryGeneratorAction.s: src/GENIEPrimaryGeneratorAction.cc.s
.PHONY : src/GENIEPrimaryGeneratorAction.s

# target to generate assembly for a file
src/GENIEPrimaryGeneratorAction.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/FLArE.dir/build.make CMakeFiles/FLArE.dir/src/GENIEPrimaryGeneratorAction.cc.s
.PHONY : src/GENIEPrimaryGeneratorAction.cc.s

src/LArBoxHit.o: src/LArBoxHit.cc.o
.PHONY : src/LArBoxHit.o

# target to build an object file
src/LArBoxHit.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/FLArE.dir/build.make CMakeFiles/FLArE.dir/src/LArBoxHit.cc.o
.PHONY : src/LArBoxHit.cc.o

src/LArBoxHit.i: src/LArBoxHit.cc.i
.PHONY : src/LArBoxHit.i

# target to preprocess a source file
src/LArBoxHit.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/FLArE.dir/build.make CMakeFiles/FLArE.dir/src/LArBoxHit.cc.i
.PHONY : src/LArBoxHit.cc.i

src/LArBoxHit.s: src/LArBoxHit.cc.s
.PHONY : src/LArBoxHit.s

# target to generate assembly for a file
src/LArBoxHit.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/FLArE.dir/build.make CMakeFiles/FLArE.dir/src/LArBoxHit.cc.s
.PHONY : src/LArBoxHit.cc.s

src/LArBoxSD.o: src/LArBoxSD.cc.o
.PHONY : src/LArBoxSD.o

# target to build an object file
src/LArBoxSD.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/FLArE.dir/build.make CMakeFiles/FLArE.dir/src/LArBoxSD.cc.o
.PHONY : src/LArBoxSD.cc.o

src/LArBoxSD.i: src/LArBoxSD.cc.i
.PHONY : src/LArBoxSD.i

# target to preprocess a source file
src/LArBoxSD.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/FLArE.dir/build.make CMakeFiles/FLArE.dir/src/LArBoxSD.cc.i
.PHONY : src/LArBoxSD.cc.i

src/LArBoxSD.s: src/LArBoxSD.cc.s
.PHONY : src/LArBoxSD.s

# target to generate assembly for a file
src/LArBoxSD.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/FLArE.dir/build.make CMakeFiles/FLArE.dir/src/LArBoxSD.cc.s
.PHONY : src/LArBoxSD.cc.s

src/PixelMap3D.o: src/PixelMap3D.cc.o
.PHONY : src/PixelMap3D.o

# target to build an object file
src/PixelMap3D.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/FLArE.dir/build.make CMakeFiles/FLArE.dir/src/PixelMap3D.cc.o
.PHONY : src/PixelMap3D.cc.o

src/PixelMap3D.i: src/PixelMap3D.cc.i
.PHONY : src/PixelMap3D.i

# target to preprocess a source file
src/PixelMap3D.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/FLArE.dir/build.make CMakeFiles/FLArE.dir/src/PixelMap3D.cc.i
.PHONY : src/PixelMap3D.cc.i

src/PixelMap3D.s: src/PixelMap3D.cc.s
.PHONY : src/PixelMap3D.s

# target to generate assembly for a file
src/PixelMap3D.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/FLArE.dir/build.make CMakeFiles/FLArE.dir/src/PixelMap3D.cc.s
.PHONY : src/PixelMap3D.cc.s

src/PrimaryGeneratorAction.o: src/PrimaryGeneratorAction.cc.o
.PHONY : src/PrimaryGeneratorAction.o

# target to build an object file
src/PrimaryGeneratorAction.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/FLArE.dir/build.make CMakeFiles/FLArE.dir/src/PrimaryGeneratorAction.cc.o
.PHONY : src/PrimaryGeneratorAction.cc.o

src/PrimaryGeneratorAction.i: src/PrimaryGeneratorAction.cc.i
.PHONY : src/PrimaryGeneratorAction.i

# target to preprocess a source file
src/PrimaryGeneratorAction.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/FLArE.dir/build.make CMakeFiles/FLArE.dir/src/PrimaryGeneratorAction.cc.i
.PHONY : src/PrimaryGeneratorAction.cc.i

src/PrimaryGeneratorAction.s: src/PrimaryGeneratorAction.cc.s
.PHONY : src/PrimaryGeneratorAction.s

# target to generate assembly for a file
src/PrimaryGeneratorAction.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/FLArE.dir/build.make CMakeFiles/FLArE.dir/src/PrimaryGeneratorAction.cc.s
.PHONY : src/PrimaryGeneratorAction.cc.s

src/PrimaryGeneratorMessenger.o: src/PrimaryGeneratorMessenger.cc.o
.PHONY : src/PrimaryGeneratorMessenger.o

# target to build an object file
src/PrimaryGeneratorMessenger.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/FLArE.dir/build.make CMakeFiles/FLArE.dir/src/PrimaryGeneratorMessenger.cc.o
.PHONY : src/PrimaryGeneratorMessenger.cc.o

src/PrimaryGeneratorMessenger.i: src/PrimaryGeneratorMessenger.cc.i
.PHONY : src/PrimaryGeneratorMessenger.i

# target to preprocess a source file
src/PrimaryGeneratorMessenger.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/FLArE.dir/build.make CMakeFiles/FLArE.dir/src/PrimaryGeneratorMessenger.cc.i
.PHONY : src/PrimaryGeneratorMessenger.cc.i

src/PrimaryGeneratorMessenger.s: src/PrimaryGeneratorMessenger.cc.s
.PHONY : src/PrimaryGeneratorMessenger.s

# target to generate assembly for a file
src/PrimaryGeneratorMessenger.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/FLArE.dir/build.make CMakeFiles/FLArE.dir/src/PrimaryGeneratorMessenger.cc.s
.PHONY : src/PrimaryGeneratorMessenger.cc.s

src/PrimaryParticleInformation.o: src/PrimaryParticleInformation.cc.o
.PHONY : src/PrimaryParticleInformation.o

# target to build an object file
src/PrimaryParticleInformation.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/FLArE.dir/build.make CMakeFiles/FLArE.dir/src/PrimaryParticleInformation.cc.o
.PHONY : src/PrimaryParticleInformation.cc.o

src/PrimaryParticleInformation.i: src/PrimaryParticleInformation.cc.i
.PHONY : src/PrimaryParticleInformation.i

# target to preprocess a source file
src/PrimaryParticleInformation.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/FLArE.dir/build.make CMakeFiles/FLArE.dir/src/PrimaryParticleInformation.cc.i
.PHONY : src/PrimaryParticleInformation.cc.i

src/PrimaryParticleInformation.s: src/PrimaryParticleInformation.cc.s
.PHONY : src/PrimaryParticleInformation.s

# target to generate assembly for a file
src/PrimaryParticleInformation.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/FLArE.dir/build.make CMakeFiles/FLArE.dir/src/PrimaryParticleInformation.cc.s
.PHONY : src/PrimaryParticleInformation.cc.s

src/RunAction.o: src/RunAction.cc.o
.PHONY : src/RunAction.o

# target to build an object file
src/RunAction.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/FLArE.dir/build.make CMakeFiles/FLArE.dir/src/RunAction.cc.o
.PHONY : src/RunAction.cc.o

src/RunAction.i: src/RunAction.cc.i
.PHONY : src/RunAction.i

# target to preprocess a source file
src/RunAction.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/FLArE.dir/build.make CMakeFiles/FLArE.dir/src/RunAction.cc.i
.PHONY : src/RunAction.cc.i

src/RunAction.s: src/RunAction.cc.s
.PHONY : src/RunAction.s

# target to generate assembly for a file
src/RunAction.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/FLArE.dir/build.make CMakeFiles/FLArE.dir/src/RunAction.cc.s
.PHONY : src/RunAction.cc.s

src/StackingAction.o: src/StackingAction.cc.o
.PHONY : src/StackingAction.o

# target to build an object file
src/StackingAction.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/FLArE.dir/build.make CMakeFiles/FLArE.dir/src/StackingAction.cc.o
.PHONY : src/StackingAction.cc.o

src/StackingAction.i: src/StackingAction.cc.i
.PHONY : src/StackingAction.i

# target to preprocess a source file
src/StackingAction.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/FLArE.dir/build.make CMakeFiles/FLArE.dir/src/StackingAction.cc.i
.PHONY : src/StackingAction.cc.i

src/StackingAction.s: src/StackingAction.cc.s
.PHONY : src/StackingAction.s

# target to generate assembly for a file
src/StackingAction.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/FLArE.dir/build.make CMakeFiles/FLArE.dir/src/StackingAction.cc.s
.PHONY : src/StackingAction.cc.s

src/SteppingAction.o: src/SteppingAction.cc.o
.PHONY : src/SteppingAction.o

# target to build an object file
src/SteppingAction.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/FLArE.dir/build.make CMakeFiles/FLArE.dir/src/SteppingAction.cc.o
.PHONY : src/SteppingAction.cc.o

src/SteppingAction.i: src/SteppingAction.cc.i
.PHONY : src/SteppingAction.i

# target to preprocess a source file
src/SteppingAction.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/FLArE.dir/build.make CMakeFiles/FLArE.dir/src/SteppingAction.cc.i
.PHONY : src/SteppingAction.cc.i

src/SteppingAction.s: src/SteppingAction.cc.s
.PHONY : src/SteppingAction.s

# target to generate assembly for a file
src/SteppingAction.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/FLArE.dir/build.make CMakeFiles/FLArE.dir/src/SteppingAction.cc.s
.PHONY : src/SteppingAction.cc.s

src/geometry/FASERnu2DetectorConstruction.o: src/geometry/FASERnu2DetectorConstruction.cc.o
.PHONY : src/geometry/FASERnu2DetectorConstruction.o

# target to build an object file
src/geometry/FASERnu2DetectorConstruction.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/FLArE.dir/build.make CMakeFiles/FLArE.dir/src/geometry/FASERnu2DetectorConstruction.cc.o
.PHONY : src/geometry/FASERnu2DetectorConstruction.cc.o

src/geometry/FASERnu2DetectorConstruction.i: src/geometry/FASERnu2DetectorConstruction.cc.i
.PHONY : src/geometry/FASERnu2DetectorConstruction.i

# target to preprocess a source file
src/geometry/FASERnu2DetectorConstruction.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/FLArE.dir/build.make CMakeFiles/FLArE.dir/src/geometry/FASERnu2DetectorConstruction.cc.i
.PHONY : src/geometry/FASERnu2DetectorConstruction.cc.i

src/geometry/FASERnu2DetectorConstruction.s: src/geometry/FASERnu2DetectorConstruction.cc.s
.PHONY : src/geometry/FASERnu2DetectorConstruction.s

# target to generate assembly for a file
src/geometry/FASERnu2DetectorConstruction.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/FLArE.dir/build.make CMakeFiles/FLArE.dir/src/geometry/FASERnu2DetectorConstruction.cc.s
.PHONY : src/geometry/FASERnu2DetectorConstruction.cc.s

src/geometry/FLArEDetectorConstruction.o: src/geometry/FLArEDetectorConstruction.cc.o
.PHONY : src/geometry/FLArEDetectorConstruction.o

# target to build an object file
src/geometry/FLArEDetectorConstruction.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/FLArE.dir/build.make CMakeFiles/FLArE.dir/src/geometry/FLArEDetectorConstruction.cc.o
.PHONY : src/geometry/FLArEDetectorConstruction.cc.o

src/geometry/FLArEDetectorConstruction.i: src/geometry/FLArEDetectorConstruction.cc.i
.PHONY : src/geometry/FLArEDetectorConstruction.i

# target to preprocess a source file
src/geometry/FLArEDetectorConstruction.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/FLArE.dir/build.make CMakeFiles/FLArE.dir/src/geometry/FLArEDetectorConstruction.cc.i
.PHONY : src/geometry/FLArEDetectorConstruction.cc.i

src/geometry/FLArEDetectorConstruction.s: src/geometry/FLArEDetectorConstruction.cc.s
.PHONY : src/geometry/FLArEDetectorConstruction.s

# target to generate assembly for a file
src/geometry/FLArEDetectorConstruction.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/FLArE.dir/build.make CMakeFiles/FLArE.dir/src/geometry/FLArEDetectorConstruction.cc.s
.PHONY : src/geometry/FLArEDetectorConstruction.cc.s

src/geometry/FORMOSADetectorConstruction.o: src/geometry/FORMOSADetectorConstruction.cc.o
.PHONY : src/geometry/FORMOSADetectorConstruction.o

# target to build an object file
src/geometry/FORMOSADetectorConstruction.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/FLArE.dir/build.make CMakeFiles/FLArE.dir/src/geometry/FORMOSADetectorConstruction.cc.o
.PHONY : src/geometry/FORMOSADetectorConstruction.cc.o

src/geometry/FORMOSADetectorConstruction.i: src/geometry/FORMOSADetectorConstruction.cc.i
.PHONY : src/geometry/FORMOSADetectorConstruction.i

# target to preprocess a source file
src/geometry/FORMOSADetectorConstruction.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/FLArE.dir/build.make CMakeFiles/FLArE.dir/src/geometry/FORMOSADetectorConstruction.cc.i
.PHONY : src/geometry/FORMOSADetectorConstruction.cc.i

src/geometry/FORMOSADetectorConstruction.s: src/geometry/FORMOSADetectorConstruction.cc.s
.PHONY : src/geometry/FORMOSADetectorConstruction.s

# target to generate assembly for a file
src/geometry/FORMOSADetectorConstruction.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/FLArE.dir/build.make CMakeFiles/FLArE.dir/src/geometry/FORMOSADetectorConstruction.cc.s
.PHONY : src/geometry/FORMOSADetectorConstruction.cc.s

src/geometry/GeometricalParameters.o: src/geometry/GeometricalParameters.cc.o
.PHONY : src/geometry/GeometricalParameters.o

# target to build an object file
src/geometry/GeometricalParameters.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/FLArE.dir/build.make CMakeFiles/FLArE.dir/src/geometry/GeometricalParameters.cc.o
.PHONY : src/geometry/GeometricalParameters.cc.o

src/geometry/GeometricalParameters.i: src/geometry/GeometricalParameters.cc.i
.PHONY : src/geometry/GeometricalParameters.i

# target to preprocess a source file
src/geometry/GeometricalParameters.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/FLArE.dir/build.make CMakeFiles/FLArE.dir/src/geometry/GeometricalParameters.cc.i
.PHONY : src/geometry/GeometricalParameters.cc.i

src/geometry/GeometricalParameters.s: src/geometry/GeometricalParameters.cc.s
.PHONY : src/geometry/GeometricalParameters.s

# target to generate assembly for a file
src/geometry/GeometricalParameters.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/FLArE.dir/build.make CMakeFiles/FLArE.dir/src/geometry/GeometricalParameters.cc.s
.PHONY : src/geometry/GeometricalParameters.cc.s

src/geometry/SpectrometerMagnetConstruction.o: src/geometry/SpectrometerMagnetConstruction.cc.o
.PHONY : src/geometry/SpectrometerMagnetConstruction.o

# target to build an object file
src/geometry/SpectrometerMagnetConstruction.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/FLArE.dir/build.make CMakeFiles/FLArE.dir/src/geometry/SpectrometerMagnetConstruction.cc.o
.PHONY : src/geometry/SpectrometerMagnetConstruction.cc.o

src/geometry/SpectrometerMagnetConstruction.i: src/geometry/SpectrometerMagnetConstruction.cc.i
.PHONY : src/geometry/SpectrometerMagnetConstruction.i

# target to preprocess a source file
src/geometry/SpectrometerMagnetConstruction.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/FLArE.dir/build.make CMakeFiles/FLArE.dir/src/geometry/SpectrometerMagnetConstruction.cc.i
.PHONY : src/geometry/SpectrometerMagnetConstruction.cc.i

src/geometry/SpectrometerMagnetConstruction.s: src/geometry/SpectrometerMagnetConstruction.cc.s
.PHONY : src/geometry/SpectrometerMagnetConstruction.s

# target to generate assembly for a file
src/geometry/SpectrometerMagnetConstruction.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/FLArE.dir/build.make CMakeFiles/FLArE.dir/src/geometry/SpectrometerMagnetConstruction.cc.s
.PHONY : src/geometry/SpectrometerMagnetConstruction.cc.s

src/reco/CircleFit.o: src/reco/CircleFit.cc.o
.PHONY : src/reco/CircleFit.o

# target to build an object file
src/reco/CircleFit.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/FLArE.dir/build.make CMakeFiles/FLArE.dir/src/reco/CircleFit.cc.o
.PHONY : src/reco/CircleFit.cc.o

src/reco/CircleFit.i: src/reco/CircleFit.cc.i
.PHONY : src/reco/CircleFit.i

# target to preprocess a source file
src/reco/CircleFit.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/FLArE.dir/build.make CMakeFiles/FLArE.dir/src/reco/CircleFit.cc.i
.PHONY : src/reco/CircleFit.cc.i

src/reco/CircleFit.s: src/reco/CircleFit.cc.s
.PHONY : src/reco/CircleFit.s

# target to generate assembly for a file
src/reco/CircleFit.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/FLArE.dir/build.make CMakeFiles/FLArE.dir/src/reco/CircleFit.cc.s
.PHONY : src/reco/CircleFit.cc.s

src/reco/Cluster3D.o: src/reco/Cluster3D.cc.o
.PHONY : src/reco/Cluster3D.o

# target to build an object file
src/reco/Cluster3D.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/FLArE.dir/build.make CMakeFiles/FLArE.dir/src/reco/Cluster3D.cc.o
.PHONY : src/reco/Cluster3D.cc.o

src/reco/Cluster3D.i: src/reco/Cluster3D.cc.i
.PHONY : src/reco/Cluster3D.i

# target to preprocess a source file
src/reco/Cluster3D.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/FLArE.dir/build.make CMakeFiles/FLArE.dir/src/reco/Cluster3D.cc.i
.PHONY : src/reco/Cluster3D.cc.i

src/reco/Cluster3D.s: src/reco/Cluster3D.cc.s
.PHONY : src/reco/Cluster3D.s

# target to generate assembly for a file
src/reco/Cluster3D.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/FLArE.dir/build.make CMakeFiles/FLArE.dir/src/reco/Cluster3D.cc.s
.PHONY : src/reco/Cluster3D.cc.s

src/reco/Hough2P.o: src/reco/Hough2P.cc.o
.PHONY : src/reco/Hough2P.o

# target to build an object file
src/reco/Hough2P.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/FLArE.dir/build.make CMakeFiles/FLArE.dir/src/reco/Hough2P.cc.o
.PHONY : src/reco/Hough2P.cc.o

src/reco/Hough2P.i: src/reco/Hough2P.cc.i
.PHONY : src/reco/Hough2P.i

# target to preprocess a source file
src/reco/Hough2P.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/FLArE.dir/build.make CMakeFiles/FLArE.dir/src/reco/Hough2P.cc.i
.PHONY : src/reco/Hough2P.cc.i

src/reco/Hough2P.s: src/reco/Hough2P.cc.s
.PHONY : src/reco/Hough2P.s

# target to generate assembly for a file
src/reco/Hough2P.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/FLArE.dir/build.make CMakeFiles/FLArE.dir/src/reco/Hough2P.cc.s
.PHONY : src/reco/Hough2P.cc.s

src/reco/LinearFit.o: src/reco/LinearFit.cc.o
.PHONY : src/reco/LinearFit.o

# target to build an object file
src/reco/LinearFit.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/FLArE.dir/build.make CMakeFiles/FLArE.dir/src/reco/LinearFit.cc.o
.PHONY : src/reco/LinearFit.cc.o

src/reco/LinearFit.i: src/reco/LinearFit.cc.i
.PHONY : src/reco/LinearFit.i

# target to preprocess a source file
src/reco/LinearFit.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/FLArE.dir/build.make CMakeFiles/FLArE.dir/src/reco/LinearFit.cc.i
.PHONY : src/reco/LinearFit.cc.i

src/reco/LinearFit.s: src/reco/LinearFit.cc.s
.PHONY : src/reco/LinearFit.s

# target to generate assembly for a file
src/reco/LinearFit.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/FLArE.dir/build.make CMakeFiles/FLArE.dir/src/reco/LinearFit.cc.s
.PHONY : src/reco/LinearFit.cc.s

src/reco/PCAAnalysis3D.o: src/reco/PCAAnalysis3D.cc.o
.PHONY : src/reco/PCAAnalysis3D.o

# target to build an object file
src/reco/PCAAnalysis3D.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/FLArE.dir/build.make CMakeFiles/FLArE.dir/src/reco/PCAAnalysis3D.cc.o
.PHONY : src/reco/PCAAnalysis3D.cc.o

src/reco/PCAAnalysis3D.i: src/reco/PCAAnalysis3D.cc.i
.PHONY : src/reco/PCAAnalysis3D.i

# target to preprocess a source file
src/reco/PCAAnalysis3D.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/FLArE.dir/build.make CMakeFiles/FLArE.dir/src/reco/PCAAnalysis3D.cc.i
.PHONY : src/reco/PCAAnalysis3D.cc.i

src/reco/PCAAnalysis3D.s: src/reco/PCAAnalysis3D.cc.s
.PHONY : src/reco/PCAAnalysis3D.s

# target to generate assembly for a file
src/reco/PCAAnalysis3D.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/FLArE.dir/build.make CMakeFiles/FLArE.dir/src/reco/PCAAnalysis3D.cc.s
.PHONY : src/reco/PCAAnalysis3D.cc.s

src/reco/ShowerLID.o: src/reco/ShowerLID.cc.o
.PHONY : src/reco/ShowerLID.o

# target to build an object file
src/reco/ShowerLID.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/FLArE.dir/build.make CMakeFiles/FLArE.dir/src/reco/ShowerLID.cc.o
.PHONY : src/reco/ShowerLID.cc.o

src/reco/ShowerLID.i: src/reco/ShowerLID.cc.i
.PHONY : src/reco/ShowerLID.i

# target to preprocess a source file
src/reco/ShowerLID.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/FLArE.dir/build.make CMakeFiles/FLArE.dir/src/reco/ShowerLID.cc.i
.PHONY : src/reco/ShowerLID.cc.i

src/reco/ShowerLID.s: src/reco/ShowerLID.cc.s
.PHONY : src/reco/ShowerLID.s

# target to generate assembly for a file
src/reco/ShowerLID.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/FLArE.dir/build.make CMakeFiles/FLArE.dir/src/reco/ShowerLID.cc.s
.PHONY : src/reco/ShowerLID.cc.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... FLArE"
	@echo "... FLArE.o"
	@echo "... FLArE.i"
	@echo "... FLArE.s"
	@echo "... src/ActionInitialization.o"
	@echo "... src/ActionInitialization.i"
	@echo "... src/ActionInitialization.s"
	@echo "... src/AnalysisManager.o"
	@echo "... src/AnalysisManager.i"
	@echo "... src/AnalysisManager.s"
	@echo "... src/AnalysisManagerMessenger.o"
	@echo "... src/AnalysisManagerMessenger.i"
	@echo "... src/AnalysisManagerMessenger.s"
	@echo "... src/DetectorConstruction.o"
	@echo "... src/DetectorConstruction.i"
	@echo "... src/DetectorConstruction.s"
	@echo "... src/DetectorConstructionMaterial.o"
	@echo "... src/DetectorConstructionMaterial.i"
	@echo "... src/DetectorConstructionMaterial.s"
	@echo "... src/DetectorConstructionMessenger.o"
	@echo "... src/DetectorConstructionMessenger.i"
	@echo "... src/DetectorConstructionMessenger.s"
	@echo "... src/EventAction.o"
	@echo "... src/EventAction.i"
	@echo "... src/EventAction.s"
	@echo "... src/FLArEPhysicsList.o"
	@echo "... src/FLArEPhysicsList.i"
	@echo "... src/FLArEPhysicsList.s"
	@echo "... src/FLArETrackInformation.o"
	@echo "... src/FLArETrackInformation.i"
	@echo "... src/FLArETrackInformation.s"
	@echo "... src/FLArETrackingAction.o"
	@echo "... src/FLArETrackingAction.i"
	@echo "... src/FLArETrackingAction.s"
	@echo "... src/GENIEPrimaryGeneratorAction.o"
	@echo "... src/GENIEPrimaryGeneratorAction.i"
	@echo "... src/GENIEPrimaryGeneratorAction.s"
	@echo "... src/LArBoxHit.o"
	@echo "... src/LArBoxHit.i"
	@echo "... src/LArBoxHit.s"
	@echo "... src/LArBoxSD.o"
	@echo "... src/LArBoxSD.i"
	@echo "... src/LArBoxSD.s"
	@echo "... src/PixelMap3D.o"
	@echo "... src/PixelMap3D.i"
	@echo "... src/PixelMap3D.s"
	@echo "... src/PrimaryGeneratorAction.o"
	@echo "... src/PrimaryGeneratorAction.i"
	@echo "... src/PrimaryGeneratorAction.s"
	@echo "... src/PrimaryGeneratorMessenger.o"
	@echo "... src/PrimaryGeneratorMessenger.i"
	@echo "... src/PrimaryGeneratorMessenger.s"
	@echo "... src/PrimaryParticleInformation.o"
	@echo "... src/PrimaryParticleInformation.i"
	@echo "... src/PrimaryParticleInformation.s"
	@echo "... src/RunAction.o"
	@echo "... src/RunAction.i"
	@echo "... src/RunAction.s"
	@echo "... src/StackingAction.o"
	@echo "... src/StackingAction.i"
	@echo "... src/StackingAction.s"
	@echo "... src/SteppingAction.o"
	@echo "... src/SteppingAction.i"
	@echo "... src/SteppingAction.s"
	@echo "... src/geometry/FASERnu2DetectorConstruction.o"
	@echo "... src/geometry/FASERnu2DetectorConstruction.i"
	@echo "... src/geometry/FASERnu2DetectorConstruction.s"
	@echo "... src/geometry/FLArEDetectorConstruction.o"
	@echo "... src/geometry/FLArEDetectorConstruction.i"
	@echo "... src/geometry/FLArEDetectorConstruction.s"
	@echo "... src/geometry/FORMOSADetectorConstruction.o"
	@echo "... src/geometry/FORMOSADetectorConstruction.i"
	@echo "... src/geometry/FORMOSADetectorConstruction.s"
	@echo "... src/geometry/GeometricalParameters.o"
	@echo "... src/geometry/GeometricalParameters.i"
	@echo "... src/geometry/GeometricalParameters.s"
	@echo "... src/geometry/SpectrometerMagnetConstruction.o"
	@echo "... src/geometry/SpectrometerMagnetConstruction.i"
	@echo "... src/geometry/SpectrometerMagnetConstruction.s"
	@echo "... src/reco/CircleFit.o"
	@echo "... src/reco/CircleFit.i"
	@echo "... src/reco/CircleFit.s"
	@echo "... src/reco/Cluster3D.o"
	@echo "... src/reco/Cluster3D.i"
	@echo "... src/reco/Cluster3D.s"
	@echo "... src/reco/Hough2P.o"
	@echo "... src/reco/Hough2P.i"
	@echo "... src/reco/Hough2P.s"
	@echo "... src/reco/LinearFit.o"
	@echo "... src/reco/LinearFit.i"
	@echo "... src/reco/LinearFit.s"
	@echo "... src/reco/PCAAnalysis3D.o"
	@echo "... src/reco/PCAAnalysis3D.i"
	@echo "... src/reco/PCAAnalysis3D.s"
	@echo "... src/reco/ShowerLID.o"
	@echo "... src/reco/ShowerLID.i"
	@echo "... src/reco/ShowerLID.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

