# define detector material before run initialization
/control/execute macros/geometry_options/FPF_hall_Reference.mac

/run/initialize
/random/setSeeds 324199 420475

# define particle gun options
/gps/verbose 0
/gps/pos/type Point
/gps/pos/centre 0 0 -2.5 m
/gps/direction 0 0 1
/gps/particle pi0
/gps/ene/mono 24.865388 GeV

# define output options
/histo/save3DEvd false
/histo/save2DEvd false
/histo/saveHit false
/histo/fileName pi0_momentum_25GeV.root

# shoot 1 particles
/run/beamOn 1
