# define detector material before run initialization
/det/material LAr

/run/initialize
#/control/execute macros/vis.mac

/gps/verbose 0
/gps/direction 0 0 1

/gps/pos/type Volume
/gps/pos/shape Cylinder
/gps/pos/rot1 1 0 0 
/gps/pos/rot2 0 1 0
/gps/pos/radius 0.1 mm
/gps/pos/centre 0 0 0 m
/gps/pos/halfz 3.5 m

# variables
/gps/particle tau-
/gps/ene/mono 1000 GeV
/histo/fileName 1000GeV.root
/run/beamOn 5000
