#
# Macro file for the initialization phase of
#
# Sets some default verbose
# and initializes the graphic.
#
/control/verbose 2
/run/verbose 2
#
/det/material LAr
#
/run/initialize
#
# Use this open statement to create an OpenGL view:
/vis/open OGL 600x600-0+0
#
# Use this open statement to create a .prim file suitable for
# viewing in DAWN:
#/vis/open DAWNFILE
#
# Use this open statement to create a .heprep file suitable for
# viewing in HepRApp:
#/vis/open HepRepFile
#
# Use this open statement to create a .wrl file suitable for
# viewing in a VRML viewer:
#/vis/open VRML2FILE
#
# Disable auto refresh and quieten vis messages whilst scene and
# trajectories are established:
/vis/viewer/set/autoRefresh false
/vis/verbose errors
#
# Draw geometry:
/vis/drawVolume
#
# Specify view angle:
/vis/viewer/set/viewpointThetaPhi 90 180 
#
#/vis/viewer/pan 4 -1
# Specify zoom value:
/vis/viewer/zoom 4
/vis/viewer/scale 1 2 1
/vis/viewer/set/background white
#
# Specify style (surface or wireframe):
#/vis/viewer/set/style wireframe
#
# Draw coordinate axes:
#/vis/scene/add/axes 0 0 0 20 m
#
# Draw smooth trajectories at end of event, showing trajectory points
# as markers 2 pixels wide:
/vis/scene/add/trajectories smooth
/vis/modeling/trajectories/create/drawByCharge
#/vis/modeling/trajectories/drawByCharge-0/default/setDrawStepPts true
#/vis/modeling/trajectories/drawByCharge-0/default/setStepPtsSize 2
# (if too many tracks cause core dump => /tracking/storeTrajectory 0)
#
# Draw hits at end of event:
#/vis/scene/add/hits
#
# To draw only gammas:
/vis/filtering/trajectories/create/particleFilter
/vis/filtering/trajectories/particleFilter-0/add gamma
#/vis/filtering/trajectories/particleFilter-0/add nu_tau
#/vis/filtering/trajectories/particleFilter-0/add anti_nu_mu
#/vis/filtering/trajectories/particleFilter-0/add neutron
#
# To invert the above, drawing all particles except gammas,
# keep the above two lines but also add:
/vis/filtering/trajectories/particleFilter-0/invert true
#
# Many other options are available with /vis/modeling and /vis/filtering.
# For example, to select colour by particle ID:
#/vis/modeling/trajectories/create/drawByParticleID
#/vis/modeling/trajectories/drawByParticleID-0/set e- blue
#
# To superimpose all of the events from a given run:
/vis/scene/endOfEventAction accumulate
#
# Re-establish auto refreshing and verbosity:
/vis/viewer/set/autoRefresh true
/vis/verbose warnings
#
# For file-based drivers, use this to create an empty detector view:
#/vis/viewer/flush
#
# set magnetic field for visualization only, and limit 
# the step for a proper visualization of the tracjectories
#
#/calor/setField 4 tesla
#/tracking/stepMax 1 m
#/tracking/stepMax 0.25 cm

/gps/verbose 1
/gps/particle tau-
/gps/ene/mono 1000 GeV
/gps/direction 0 0 1

#/gps/pos/type Volume
#/gps/pos/shape Cylinder
#/gps/pos/rot1 1 0 0 
#/gps/pos/rot2 0 1 0
#/gps/pos/radius 0.1 mm
#/gps/pos/centre 0 0 0 m
#/gps/pos/halfz 3.5 m

#/gps/pos/type Plane
#/gps/pos/rot1 1 0 0 
#/gps/pos/rot2 0 1 0
#/gps/pos/shape Circle
#/gps/pos/centre 0. 0. -25. m
#/gps/pos/radius 1. cm

/gps/pos/type Point
/gps/pos/centre 0. 0. -2.5 m
