#
# Macro file for the initialization phase of
#
# Sets some default verbose
# and initializes the graphic.
#
/control/verbose 2
/run/verbose 2

/control/execute macros/geometry_options/FPF_hall_Reference.mac
#/control/execute macros/geometry_options/FPF_hall_Reference_CP.mac
#/control/execute macros/geometry_options/FPF_hall_Option1a_FORMOSAlast.mac
#/control/execute macros/geometry_options/FPF_hall_Option1a_FORMOSAlast_CP.mac
#/control/execute macros/geometry_options/FPF_hall_Option1b_FORMOSAunder.mac
#/control/execute macros/geometry_options/FPF_hall_Option1b_FORMOSAunder_CP.mac
#/control/execute macros/geometry_options/FPF_hall_Option2_FASERnufirst.mac
#/control/execute macros/geometry_options/FPF_hall_Option2_FASERnufirst_CP.mac

#
/run/initialize
#

#/vis/open DAWNFILE
# Use this open statement to create an OpenGL view:
/vis/open OGLIX 1000x800-0+0
/vis/ogl/set/displayListLimit 5000000
#
# Disable auto refresh and quieten vis messages whilst scene and
# trajectories are established:
/vis/viewer/set/autoRefresh false
/vis/verbose errors
#
# Draw geometry:
/vis/drawVolume
#
# Specify view angle:
#/vis/viewer/set/viewpointThetaPhi 90 180  # cross-section view
#/vis/viewer/set/viewpointThetaPhi 70 20   # view with neutrinos enter from the right
/vis/viewer/set/viewpointThetaPhi 70 200  # view aligns with Yichen's engineering drawing
#
/vis/viewer/pan 0 0
/vis/viewer/zoom 1
/vis/viewer/scale 1 1 1
/vis/viewer/set/background white
#/vis/viewer/set/background white ! ! 0.
#
# Specify style (surface or wireframe):
#/vis/viewer/set/style wireframe
#
# Draw coordinate axes:
#/vis/scene/add/axes 0 0 0 20 m
#
# Draw smooth trajectories at end of event, showing trajectory points
# as markers 2 pixels wide:
/vis/scene/add/trajectories smooth
#/vis/modeling/trajectories/create/drawByCharge
#/vis/modeling/trajectories/drawByCharge-0/default/setDrawStepPts true
#/vis/modeling/trajectories/drawByCharge-0/default/setStepPtsSize 2
# (if too many tracks cause core dump => /tracking/storeTrajectory 0)
#
# Draw hits at end of event:
#/vis/scene/add/hits
#
# to select colour by particle ID:
/vis/modeling/trajectories/create/drawByParticleID
/vis/modeling/trajectories/drawByParticleID-0/set e- red
/vis/modeling/trajectories/drawByParticleID-0/set e+ blue
/vis/modeling/trajectories/drawByParticleID-0/set proton cyan
/vis/modeling/trajectories/drawByParticleID-0/set gamma green
/vis/modeling/trajectories/drawByParticleID-0/set neutron yellow
/vis/modeling/trajectories/drawByParticleID-0/set pi- violet
/vis/modeling/trajectories/drawByParticleID-0/set pi+ orange
/vis/modeling/trajectories/drawByParticleID-0/set pi0 brown 
/vis/modeling/trajectories/drawByParticleID-0/set mu- magenta

/vis/filtering/trajectories/create/particleFilter
/vis/filtering/trajectories/particleFilter-0/add gamma
/vis/filtering/trajectories/particleFilter-0/add neutron
/vis/filtering/trajectories/particleFilter-0/invert true
#/vis/filtering/trajectories/create/attributeFilter
#/vis/filtering/trajectories/attributeFilter-0/setAttribute IMag
#/vis/filtering/trajectories/attributeFilter-0/addInterval 1 GeV 1000 GeV
#
# To superimpose all of the events from a given run:
/vis/scene/endOfEventAction accumulate
#
# Re-establish auto refreshing and verbosity:
/vis/viewer/set/autoRefresh true
/vis/verbose warnings
#
# For file-based drivers, use this to create an empty detector view:
#/vis/viewer/flush
#
